// Code generated by "stringer -type UpdateKind -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UpdateVulnerability-1]
	_ = x[UpdateEnrichment-2]
}

const _UpdateKind_name = "vulnerabilityenrichment"

var _UpdateKind_index = [...]uint8{0, 13, 23}

func (i UpdateKind) String() string {
	i -= 1
	if i < 0 || i >= UpdateKind(len(_UpdateKind_index)-1) {
		return "UpdateKind(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _UpdateKind_name[_UpdateKind_index[i]:_UpdateKind_index[i+1]]
}
