// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"encoding/json"

	"github.com/quay/claircore"
)

type Distribution struct {
	ID string `json:"id"`
}

type Enrichment struct {
	Type       string            `json:"type"`
	Enrichment []json.RawMessage `json:"enrichment"`
}

type Environment struct {
	ID string `json:"id"`
}

type Package struct {
	ID string `json:"id"`
}

type PackageReport struct {
	ID            string          `json:"id"`
	Vulnerability []Vulnerability `json:"vulnerability"`
	Distribution  *Distribution   `json:"distribution"`
	Repository    []Repository    `json:"repository"`
}

type PackageVulnerability struct {
	ID              string   `json:"id"`
	Vulnerabilities []string `json:"vulnerabilities"`
}

type ReportResponse struct {
	Packages    []PackageReport `json:"packages"`
	Enrichments []Enrichment    `json:"enrichments"`
}

type Repository struct {
	ID string `json:"id"`
}

type Vulnerability struct {
	ID string `json:"id"`
}

type VulnerabilityReport struct {
	Digest                 claircore.Digest       `json:"digest"`
	Packages               []Package              `json:"packages"`
	Distributions          []Distribution         `json:"distributions"`
	Repositories           []Repository           `json:"repositories"`
	Environments           []Environment          `json:"environments"`
	Vulnerabilities        []Vulnerability        `json:"vulnerabilities"`
	Enrichments            []Enrichment           `json:"enrichments"`
	PackageVulnerabilities []PackageVulnerability `json:"package_vulnerabilities"`
}
