// Code generated by "stringer -type Scheme -trimprefix Scheme"; DO NOT EDIT.

package codec

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SchemeV1-1]
}

const _Scheme_name = "V1"

var _Scheme_index = [...]uint8{0, 2}

func (i Scheme) String() string {
	i -= 1
	if i >= Scheme(len(_Scheme_index)-1) {
		return "Scheme(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Scheme_name[_Scheme_index[i]:_Scheme_index[i+1]]
}
