{
 "title": "Clair V4",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "rate",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "dbquantile", "label": "Database Latency Quantile", "query": "0.95,0.90,0.5,0.20,0" },
   { "name": "apiquantile", "label": "API Latency Quantile", "query": "0.95,0.90,0.5,0.20,0" },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Runtime metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Previously scanned",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(claircore_indexer_scanned_manifests{scanned_before=\"true\"}[$rate])",
     "legendFormat": "scanned"
    },
    {
     "expr": "rate(claircore_indexer_scanned_manifests{scanned_before=\"false\"}[$rate])",
     "legendFormat": "not scanned"
    }
   ]
  },
  {
   "title": "Previously scanned rate",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(claircore_indexer_scanned_manifests{scanned_before=\"true\"}[$rate])",
     "legendFormat": "scanned"
    },
    {
     "expr": "rate(claircore_indexer_scanned_manifests{scanned_before=\"false\"}[$rate])",
     "legendFormat": "not scanned"
    }
   ]
  },
  {
   "title": "Authentication",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(clair_middleware_authenticated_total{authenticated=\"false\"}[$rate])",
     "legendFormat": "Unauthenticated: {{ job }}"
    },
    {
     "expr": "rate(clair_middleware_authenticated_total{authenticated=\"true\"}[$rate])",
     "legendFormat": "Authenticated: {{ job }}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Database query count (indexer)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(claircore_indexer_setindexreport_total[$rate])",
     "legendFormat": "IndexReport: {{instance }}: {{ query }}"
    },
    {
     "expr": "rate(claircore_indexer_layerscanned_total[$rate])",
     "legendFormat": "LayerScanned: {{instance }}: {{ query }}"
    },
    {
     "expr": "rate(claircore_indexer_manifestscanned_total[$rate])",
     "legendFormat": "ManifestScanned: {{instance }}: {{ query }}"
    },
    {
     "expr": "rate(claircore_indexer_persistmanifest_total[$rate])",
     "legendFormat": "PersistManifest: {{instance }}: {{ query }}"
    },
    {
     "expr": "rate(claircore_indexer_registerscanners_total[$rate])",
     "legendFormat": "RegisterScanners: {{instance }}: {{ query }}"
    },
    {
     "expr": "rate(claircore_indexer_setindexreport_total[$rate])",
     "legendFormat": "SetIndexReport: {{instance }}: {{ query }}"
    }
   ]
  },
  {
   "title": "Database query duration (indexer) (p$dbquantile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile($dbquantile, rate(claircore_indexer_setindexreport_duration_seconds_bucket[$rate]))",
     "legendFormat": "IndexReport"
    },
    {
     "expr": "histogram_quantile($dbquantile, rate(claircore_indexer_layerscanned_duration_seconds_bucket[$rate]))",
     "legendFormat": "LayerScanned"
    },
    {
     "expr": "histogram_quantile($dbquantile, rate(claircore_indexer_manifestscanned_duration_seconds_bucket[$rate]))",
     "legendFormat": "ManifestScanned"
    },
    {
     "expr": "histogram_quantile($dbquantile, rate(claircore_indexer_persistmanifest_duration_seconds_bucket[$rate]))",
     "legendFormat": "PersistManifest"
    },
    {
     "expr": "histogram_quantile($dbquantile, rate(claircore_indexer_registerscanners_duration_seconds_bucket[$rate]))",
     "legendFormat": "RegisterScanners"
    },
    {
     "expr": "histogram_quantile($dbquantile, rate(claircore_indexer_setindexfinished_duration_seconds_bucket[$rate]))",
     "legendFormat": "SetIndexReport"
    }
   ]
  },
  {
   "title": "Database query count (matcher)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(claircore_vulnstore_get_total[$rate])",
     "legendFormat": "VulnStoreGet: {{instance }}: {{ query }}"
    },
    {
     "expr": "rate(claircore_vulnstore_getlatestrefs_total[$rate])",
     "legendFormat": "GetLatestRefs: {{instance }}: {{ query }}"
    },
    {
     "expr": "rate(claircore_vulnstore_getlatestupdateref_total[$rate])",
     "legendFormat": "GetLatestUpdateRef: {{instance }}: {{ query }}"
    },
    {
     "expr": "rate(claircore_vulnstore_getupdateoperations_total[$rate])",
     "legendFormat": "GetUpdateOperations: {{instance }}: {{ query }}"
    },
    {
     "expr": "rate(claircore_vulnstore_updatevulnerabilities_total[$rate])",
     "legendFormat": "UpdateVulnerabilities: {{instance }}: {{ query }}"
    }
   ]
  },
  {
   "title": "Database query duration (matcher) (p$dbquantile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile($dbquantile, rate(claircore_vulnstore_get_duration_seconds_bucket[$rate]))",
     "legendFormat": "VulnStoreGet: {{instance }}: {{ query }}"
    },
    {
     "expr": "histogram_quantile($dbquantile, rate(claircore_vulnstore_getlatestrefs_duration_seconds_bucket[$rate]))",
     "legendFormat": "GetLatestRefs: {{instance }}: {{ query }}"
    },
    {
     "expr": "histogram_quantile($dbquantile, rate(claircore_vulnstore_getlatestupdateref_duration_seconds_bucket[$rate]))",
     "legendFormat": "GetLatestUpdateRef: {{instance }}: {{ query }}"
    },
    {
     "expr": "histogram_quantile($dbquantile, rate(claircore_vulnstore_getupdateoperations_duration_seconds_bucket[$rate]))",
     "legendFormat": "GetUpdateOperations: {{instance }}: {{ query }}"
    },
    {
     "expr": "histogram_quantile($dbquantile, rate(claircore_vulnstore_updatevulnerabilities_duration_seconds_bucket[$rate]))",
     "legendFormat": "UpdateVulnerabilities: {{instance }}: {{ query }}"
    }
   ]
  },
  { "title": "API Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Vulnerability Report Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by (code) (rate(clair_http_matcher_api_v1_vulnerability_report_request_total[$rate]))",
     "legendFormat": "Status {{ code }} "
    }
   ]
  },
  {
   "title": "Vulnerability Report Request Latency (p$apiquantile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "histogram_quantile($apiquantile, rate(clair_http_matcher_api_v1_vulnerability_report_request_duration_seconds_bucket[$rate]))"
    }
   ]
  },
  {
   "title": "Create Index Report Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum by (code) (rate(clair_http_indexer_api_v1_index_report_request_total[$rate]))",
     "legendFormat": "Status {{ code }} "
    }
   ]
  },
  {
   "title": "Create Index Report Request Latency (p$apiquantile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "histogram_quantile($apiquantile, rate(clair_http_indexer_api_v1_index_report_request_duration_seconds_bucket[$rate]))"
    }
   ]
  },
  {
   "title": "Indexer State Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum by (code) (rate(clair_http_indexer_api_v1_index_state_request_total[$rate]))",
     "legendFormat": "Status {{ code }} "
    }
   ]
  },
  {
   "title": "Indexer State Request Latency (p$apiquantile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile($apiquantile, rate(clair_http_indexer_api_v1_index_state_request_duration_seconds_bucket[$rate]))"
    }
   ]
  },
  {
   "title": "Index Report Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum by (code) (rate(clair_http_indexer_api_v1_index_report_get_request_total[$rate]))",
     "legendFormat": "Status {{ code }} "
    }
   ]
  },
  {
   "title": "Index Report Request Latency (p$apiquantile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "histogram_quantile($apiquantile, rate(clair_http_indexer_api_v1_index_report_get_request_duration_seconds_bucket[$rate]))"
    }
   ]
  },
  { "title": "Memory metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Goroutine count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "{{ job }}" }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "go_memstats_heap_inuse_bytes", "legendFormat": "{{ job }}" }
   ]
  }
 ]
}