// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/v3/clairpb/clair.proto

package clairpb

import github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/googleapis/google/api"
import _ "github.com/gogo/protobuf/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Vulnerability) Validate() error {
	for _, item := range this.AffectedVersions {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("AffectedVersions", err)
			}
		}
	}
	return nil
}
func (this *Feature) Validate() error {
	for _, item := range this.Vulnerabilities {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Vulnerabilities", err)
			}
		}
	}
	return nil
}
func (this *Layer) Validate() error {
	return nil
}
func (this *ClairStatus) Validate() error {
	if this.LastUpdateTime != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.LastUpdateTime); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("LastUpdateTime", err)
		}
	}
	return nil
}
func (this *GetAncestryRequest) Validate() error {
	return nil
}
func (this *GetAncestryResponse) Validate() error {
	if this.Ancestry != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Ancestry); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Ancestry", err)
		}
	}
	if this.Status != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Status); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Status", err)
		}
	}
	return nil
}
func (this *GetAncestryResponse_Ancestry) Validate() error {
	for _, item := range this.Features {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Features", err)
			}
		}
	}
	for _, item := range this.Layers {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Layers", err)
			}
		}
	}
	return nil
}
func (this *PostAncestryRequest) Validate() error {
	for _, item := range this.Layers {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Layers", err)
			}
		}
	}
	return nil
}
func (this *PostAncestryRequest_PostLayer) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *PostAncestryResponse) Validate() error {
	if this.Status != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Status); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Status", err)
		}
	}
	return nil
}
func (this *GetNotificationRequest) Validate() error {
	return nil
}
func (this *GetNotificationResponse) Validate() error {
	if this.Notification != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Notification); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Notification", err)
		}
	}
	return nil
}
func (this *GetNotificationResponse_Notification) Validate() error {
	if this.Old != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Old); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Old", err)
		}
	}
	if this.New != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.New); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("New", err)
		}
	}
	return nil
}
func (this *PagedVulnerableAncestries) Validate() error {
	if this.Vulnerability != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Vulnerability); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Vulnerability", err)
		}
	}
	for _, item := range this.Ancestries {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Ancestries", err)
			}
		}
	}
	return nil
}
func (this *PagedVulnerableAncestries_IndexedAncestryName) Validate() error {
	return nil
}
func (this *MarkNotificationAsReadRequest) Validate() error {
	return nil
}
func (this *MarkNotificationAsReadResponse) Validate() error {
	return nil
}
