#!/bin/sh --
# \
exec jq -c -r -n -f "${0}" -- "$@"

[ inputs ] |
( [ .[] | select(.status >= 500) | .request_id ] | unique | .[] ) as $id |
[ .[] | select(.request_id == $id) ] |
	sort_by(.time) |
	.[]
