mode: indexer
log_level: debug
http_listen_addr: :80
indexer:
  connstring: host=clair-db port=5432 user=clair dbname=clair sslmode=disable
  scanlock_retry: 10
  layer_scan_concurrency: 5
  migrations: true
