mode: indexer
log_level: debug
introspection_addr: ":8089"
indexer:
  http_listen_addr: ":80"
  connstring: host=clair-db port=5432 user=clair dbname=clair sslmode=disable
  scanlock_retry: 10
  layer_scan_concurrency: 5
  migrations: true
# tracing and metrics config
trace:
  name: "jaeger"
  probability: 1
  jaeger:
    agent_endpoint: "jaeger:6831"
    service_name: "clair"
metrics:
  name: "prometheus"
