{
 "title": "Clair V4",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "rate",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "dbquantile", "label": "Database Latency Quantile", "query": "0.95,0.90,0.5,0.20,0" },
   { "name": "apiquantile", "label": "API Latency Quantile", "query": "0.95,0.90,0.5,0.20,0" },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Runtime metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Previously scanned manifests / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (scanned_before) (rate(claircore_indexer_scanned_manifests[$rate]))",
     "legendFormat": "{{scanned_before}}"
    }
   ]
  },
  {
   "title": "Previously scanned rate",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (scanned_before) (rate(claircore_indexer_scanned_manifests[$rate]))",
     "legendFormat": "{{scanned_before}}"
    }
   ]
  },
  {
   "title": "Versions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum (clair_cmd_version_info) by (job, goversion)",
     "legendFormat": "{{job}} - {{goversion}}"
    },
    {
     "expr": "sum (clair_cmd_version_info) by(job, version)",
     "legendFormat": "{{job}} clair - {{version}}"
    },
    {
     "expr": "sum (clair_cmd_version_info) by(job, claircore_version)",
     "legendFormat": "{{job}} claircore - {{claircore_version}}"
    }
   ]
  },
  {
   "title": "Ratelimiting / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(clair_http_concurrencylimited_total[$rate])",
     "legendFormat": "Endpoint: {{ endpoint }} Method: {{ method }}"
    }
   ]
  },
  { "title": "Database Indexer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Database query count (indexer)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(claircore_indexer_setindexreport_total[$rate])",
     "legendFormat": "IndexReport: {{instance }}: {{ query }}"
    },
    {
     "expr": "rate(claircore_indexer_layerscanned_total[$rate])",
     "legendFormat": "LayerScanned: {{instance }}: {{ query }}"
    },
    {
     "expr": "rate(claircore_indexer_manifestscanned_total[$rate])",
     "legendFormat": "ManifestScanned: {{instance }}: {{ query }}"
    },
    {
     "expr": "rate(claircore_indexer_persistmanifest_total[$rate])",
     "legendFormat": "PersistManifest: {{instance }}: {{ query }}"
    },
    {
     "expr": "rate(claircore_indexer_registerscanners_total[$rate])",
     "legendFormat": "RegisterScanners: {{instance }}: {{ query }}"
    },
    {
     "expr": "rate(claircore_indexer_setindexreport_total[$rate])",
     "legendFormat": "SetIndexReport: {{instance }}: {{ query }}"
    }
   ]
  },
  {
   "title": "Set index_report query duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(claircore_indexer_setindexreport_duration_seconds_bucket[5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Layer scanned query duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(claircore_indexer_layerscanned_duration_seconds_bucket[5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Persist manifest query duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(claircore_indexer_persistmanifest_duration_seconds_bucket[$rate])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Manifest scanned query duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(claircore_indexer_manifestscanned_duration_seconds_bucket[5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Register scanners query duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(claircore_indexer_registerscanners_duration_seconds_bucket[5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Set index finished query duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(claircore_indexer_setindexfinished_duration_seconds_bucket[5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Connections (Indexer)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum by (application_name) (pgxpool_idle_conns{application_name=\"libindex\"})",
     "legendFormat": "idle"
    },
    {
     "expr": "sum by (application_name) (pgxpool_max_conns{application_name=\"libindex\"})",
     "legendFormat": "max"
    },
    {
     "expr": "sum by (application_name) (pgxpool_total_conns{application_name=\"libindex\"})",
     "legendFormat": "total"
    },
    {
     "expr": "sum by (application_name) (pgxpool_acquired_conns{application_name=\"libindex\"})",
     "legendFormat": "acquired"
    }
   ]
  },
  { "title": "Database matcher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Database query count (matcher)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "rate(claircore_vulnstore_getvulnerabilities_total[$rate])",
     "legendFormat": "VulnStoreGet: {{instance }}: {{ query }}"
    },
    {
     "expr": "rate(claircore_vulnstore_getlatestrefs_total[$rate])",
     "legendFormat": "GetLatestRefs: {{instance }}: {{ query }}"
    },
    {
     "expr": "rate(claircore_vulnstore_getlatestupdateref_total[$rate])",
     "legendFormat": "GetLatestUpdateRef: {{instance }}: {{ query }}"
    },
    {
     "expr": "rate(claircore_vulnstore_getupdateoperations_total[$rate])",
     "legendFormat": "GetUpdateOperations: {{instance }}: {{ query }}"
    },
    {
     "expr": "rate(claircore_vulnstore_updatevulnerabilities_total[$rate])",
     "legendFormat": "UpdateVulnerabilities: {{instance }}: {{ query }}"
    }
   ]
  },
  {
   "title": "Get vulnerabilities latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum(rate(claircore_vulnstore_getvulnerabilities_duration_seconds_bucket[$rate])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Get latest refs latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 49 },
   "targets": [
    {
     "expr": "sum(rate(claircore_vulnstore_getlatestrefs_duration_seconds_bucket[$rate])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Get latest update refs latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 49 },
   "targets": [
    {
     "expr": "sum(rate(claircore_vulnstore_getlatestupdateref_duration_seconds_bucket[$rate])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Get update operations latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "sum(rate(claircore_vulnstore_getupdateoperations_duration_seconds_bucket[$rate])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Update vulnerabilities latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 49 },
   "targets": [
    {
     "expr": "sum(rate(claircore_vulnstore_updatevulnerabilities_duration_seconds_bucket[$rate])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Get enrichments latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 49 },
   "targets": [
    {
     "expr": "sum(rate(claircore_vulnstore_getenrichments_duration_seconds_bucket[$rate])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Database query count GC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "rate(claircore_vulnstore_gc_total[$rate])",
     "legendFormat": "GarbageCollection: {{instance }}: {{ query }}"
    }
   ]
  },
  {
   "title": "Connections (Matcher)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "sum by (application_name) (pgxpool_idle_conns{application_name=\"libvuln\"})",
     "legendFormat": "idle"
    },
    {
     "expr": "sum by (application_name) (pgxpool_max_conns{application_name=\"libvuln\"})",
     "legendFormat": "max"
    },
    {
     "expr": "sum by (application_name) (pgxpool_total_conns{application_name=\"libvuln\"})",
     "legendFormat": "total"
    },
    {
     "expr": "sum by (application_name) (pgxpool_acquired_conns{application_name=\"libvuln\"})",
     "legendFormat": "acquired"
    }
   ]
  },
  {
   "title": "GC - updateOps latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "sum(rate(claircore_vulnstore_gc_duration_seconds_bucket{query=\"updateOps\"}[$rate])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "GC - deleteVulns latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "sum(rate(claircore_vulnstore_gc_duration_seconds_bucket{query=\"deleteVulns\"}[$rate])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Database - Notifier",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database query count (notifier)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "rate(clair_notifier_created_total[$rate])",
       "legendFormat": "CreatedTotal: {{instance }}: {{ query }}"
      },
      {
       "expr": "rate(clair_notifier_failed_total[$rate])",
       "legendFormat": "NotifierFailed: {{instance }}: {{ query }}"
      },
      {
       "expr": "rate(clair_notifier_putreceipt_total[$rate])",
       "legendFormat": "NotifierPutReceipt: {{instance }}: {{ query }}"
      },
      {
       "expr": "rate(clair_notifier_receiptbyuoid_total[$rate])",
       "legendFormat": "NotifierReceiptByUOID: {{instance }}: {{ query }}"
      }
     ]
    },
    {
     "title": "Database query duration (notifier) (p$dbquantile)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "histogram_quantile($dbquantile, rate(clair_notifier_created_duration_seconds_bucket[$rate]))",
       "legendFormat": "CreatedTotal: {{instance }}: {{ query }}"
      },
      {
       "expr": "histogram_quantile($dbquantile, rate(clair_notifier_failed_duration_seconds_bucket[$rate]))",
       "legendFormat": "NotifierFailed: {{instance }}: {{ query }}"
      },
      {
       "expr": "histogram_quantile($dbquantile, rate(clair_notifier_putreceipt_duration_seconds_bucket[$rate]))",
       "legendFormat": "NotifierPutReceipt: {{instance }}: {{ query }}"
      },
      {
       "expr": "histogram_quantile($dbquantile, rate(clair_notifier_receiptbyuoid_duration_seconds_bucket[$rate]))",
       "legendFormat": "NotifierReceiptByUOID: {{instance }}: {{ query }}"
      }
     ]
    }
   ]
  },
  { "title": "API Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Vulnerability Report Requests / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "sum by (code) (rate(clair_http_matcherv1_request_total{handler=\"/matcher/api/v1/vulnerability_report/\"}[$rate]))",
     "legendFormat": "Status {{ code }} "
    }
   ]
  },
  {
   "title": "Vulnerability Report Request Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "targets": [
    {
     "expr": "sum(rate(clair_http_matcherv1_request_duration_seconds_bucket{handler=\"/matcher/api/v1/vulnerability_report/\"}[5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Create Index Report Requests / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "sum by (code) (rate(clair_http_indexerv1_request_total{handler=\"/indexer/api/v1/index_report\", method=\"post\"}[$rate]))",
     "legendFormat": "Status {{ code }} "
    }
   ]
  },
  {
   "title": "Create Index Report Request Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "targets": [
    {
     "expr": "sum(increase(clair_http_indexerv1_request_duration_seconds_bucket{method=\"post\", handler=\"/indexer/api/v1/index_report\", code=\"201\"} [5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Indexer State Requests / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "targets": [
    {
     "expr": "sum by (code) (rate(clair_http_indexerv1_request_total{handler=\"/indexer/api/v1/index_state\", method=\"get\"}[$rate]))",
     "legendFormat": "Status {{code}}"
    }
   ]
  },
  {
   "title": "Indexer State Request Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "targets": [
    {
     "expr": "sum(increase(clair_http_indexerv1_request_duration_seconds_bucket{method=\"get\", handler=\"/indexer/api/v1/index_state\"} [5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Index Report Requests / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "targets": [
    {
     "expr": "sum by (code) (rate(clair_http_indexerv1_request_total{method=\"get\", handler=\"/indexer/api/v1/index_report/:digest\"}[$rate]))",
     "legendFormat": "Status {{ code }} "
    }
   ]
  },
  {
   "title": "Index Report Request Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "targets": [
    {
     "expr": "sum(increase(clair_http_indexerv1_request_duration_seconds_bucket{method=\"get\", handler=\"/indexer/api/v1/index_report/:digest\"} [5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Index Report Bulk Deletion Requests / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "targets": [
    {
     "expr": "sum by (code) (rate(clair_http_indexerv1_request_total{method=\"delete\", handler=\"/indexer/api/v1/index_report\"}[$rate]))",
     "legendFormat": "Status {{ code }} "
    }
   ]
  },
  {
   "title": "Index Report Bulk Deletion Request Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "targets": [
    {
     "expr": "sum(increase(clair_http_indexerv1_request_duration_seconds_bucket{method=\"delete\", handler=\"/indexer/api/v1/index_report\"} [5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Index Report Deletion Requests / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
   "targets": [
    {
     "expr": "sum by (code) (rate(clair_http_indexerv1_request_total{method=\"delete\", handler=\"/indexer/api/v1/index_report/:digest\"}[$rate]))",
     "legendFormat": "Status {{ code }} "
    }
   ]
  },
  {
   "title": "Index Report Deletion Request Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
   "targets": [
    {
     "expr": "sum(increase(clair_http_indexerv1_request_duration_seconds_bucket{method=\"delete\", handler=\"/indexer/api/v1/index_report/:digest\"} [5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Get Notifications Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 130 },
   "targets": [
    {
     "expr": "sum by (code) (rate(clair_http_notifier_api_v1_notification_request_total{method=\"get\"}[$rate]))",
     "legendFormat": "Status {{ code }} "
    }
   ]
  },
  {
   "title": "Get Notification Request Latency (p$apiquantile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 130 },
   "targets": [
    {
     "expr": "histogram_quantile($apiquantile, rate(clair_http_notifier_api_v1_notification_request_duration_seconds_bucket[$rate]))"
    }
   ]
  },
  {
   "title": "Delete Notification Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 138 },
   "targets": [
    {
     "expr": "sum by (code) (rate(clair_http_notifier_api_v1_notification_request_total{method=\"delete\"}[$rate]))",
     "legendFormat": "Status {{ code }}"
    }
   ]
  },
  {
   "title": "Delete Notification Request Latency (p$apiquantile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 138 },
   "targets": [
    {
     "expr": "histogram_quantile($apiquantile, rate(clair_http_notifier_api_v1_notification_request_duration_seconds_bucket[$rate]))"
    }
   ]
  },
  { "title": "Memory metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 146 } },
  {
   "title": "Goroutine count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 147 },
   "targets": [
    { "expr": "sum by (job)(go_goroutines)", "legendFormat": "{{ job }}" }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job)(go_memstats_heap_inuse_bytes)",
     "legendFormat": "{{ job }}"
    }
   ]
  }
 ]
}