server:
  addr: :5001
  certificate: /ssl/server.pem
  key: /ssl/server.key
token:
  issuer: auth_service
  expiration: 900
users:
  "": {}
  jgsqware:
    password: $2y$05$oGKwJ8QJDLBOoTBmC/EQiefIMV1N9Yt9jpX3SqMoRqZRRql6q7yym
acl:
- match:
    account: jgsqware
  actions: ['*']
- match:
    account: /.+/
    name: ${account}/*
  actions: ['*']
- match:
    type: registry
    name: catalog
  actions: ['*']
  comment: Anonymous users can get catalog.
- match:
    account: ""
    name: /.*/
  actions: [pull]
  comment: Anonymous users can pull everything.
