name: clair
summary:  Vulnerability Static Analysis for Containers.
description:|  An open source project for the static analysis of vulnerabilities in application containers (currently including appc and docker).
  
adopt-info: clair

grade: stable
confinement: classic

architectures:
  - build-on: i386
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

apps:
  clair:
    command: bin/clair
    plugs:
      - home
      - network
      - docker
      - removable-media

parts:
  clair:
  plugin: nil 
    source: https://github.com/coreos/clair.git
    source-type: git
    override-pull: |
      git clone https://github.com/coreos/clair.git src/github.com/coreos/clair
       cd src/github.com/coreos/clair
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_committed_tag_ver="$(echo ${last_committed_tag} | sed 's/v//')"
      last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag_ver}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl set-version "$(git describe --tags | sed 's/v//')"
      override-build: |
      export GOPATH=$PWD
      cd src/github.com/coreos/clair
      env CGO_ENABLED=0 GOOS=linux \
      go build --ldflags "-s -w \
        -X 'github.com/coreos/clair/version.GitCommit=$(git rev-list -1 HEAD)' \
        -X 'github.com/coreos/clair/version.Version=$(git describe --tags --abbrev=0)'" \
        -a -installsuffix cgo -o $SNAPCRAFT_PART_INSTALL/bin/clair
    build-snaps:
      - go
    build-packages:
      - git
      - sed
