FROM registry.redhat.io/ubi8/go-toolset:latest AS build

WORKDIR /app
COPY . .

ARG clair_version

RUN GOEXPERIMENT=strictfipsruntime go build -tags strictfipsruntime -mod=mod \
	-ldflags="-s -w$(test -n "$clair_version" && printf " -X 'github.com/quay/clair/v4/cmd.Version=%s (user)'" "${clair_version}")" \
	-o . \
	-trimpath \
	./cmd/...


FROM registry.redhat.io/ubi8/ubi-minimal:latest

ARG clair_version

ENTRYPOINT ["/usr/bin/clair"]
VOLUME /config
EXPOSE 6060
WORKDIR /run

ENV CLAIR_CONF=/config/config.yaml \
    CLAIR_MODE=combo \
    SSL_CERT_DIR="/etc/ssl/certs:/etc/pki/tls/certs:/var/run/certs"

USER nobody:nobody

LABEL com.redhat.component="clair-container"
LABEL name="quay/clair-rhel8"
LABEL io.k8s.display-name="Red Hat Quay - Clair"
LABEL io.k8s.description="Clair vulnerability scanner for Red Hat Quay"
LABEL io.openshift.tags="quay,clair,security"
LABEL summary="Clair vulnerability scanner for Red Hat Quay"
LABEL description="Clair vulnerability scanner for Red Hat Quay"
LABEL vendor="Red Hat, Inc."
LABEL maintainer="quay-devel@redhat.com"

COPY --from=build /app/clair /bin/clair
COPY --from=build /app/clairctl /bin/clairctl
